CSRToolWebApp/Controllers/TerritoryController.cs
using System;
using AutoMapper;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CSRToolWebApp.Common;
using CSRToolWebApp.DataContracts.Base;
using CSRToolWebApp.Models;
using GridMvc;
using GridMvc.Filtering;
using GridMvc.Sorting;
using Newtonsoft.Json;

using Territory = CSRToolWebApp.DataContracts.Base.Territory;

namespace CSRToolWebApp.Controllers
{
    public class TerritoryController : Controller
    {
        #region Views

        public ActionResult Default()
        {

            var territoryList = GetTerritoryList();
            ViewBag.Territories = territoryList;

            var territories = FetchTerritoriesFromService();


            var model = CreateGridFromTerritoriesList(territories);

            return View(model);
        }

        private static List<SelectListItem> GetTerritoryList()
        {
            var restService = new RestService("territories");
            var json = restService.Get(new List<KeyValuePair<string, string>>());
            var dataContractTerritory = JsonConvert.DeserializeObject<List<Territory>>(json);
            var selectList =
                dataContractTerritory.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList();
            //selectList.Insert(0, new SelectListItem() { Text = string.Empty, Value = Guid.Empty.ToString() });

            return selectList;
        }


        #endregion Views

        #region Methods

        private static Grid<SimpleTerritory> CreateGridFromTerritoriesList(IEnumerable<SimpleTerritory> territories)
        {
            var grid = new Grid<SimpleTerritory>(territories.OrderBy(x => x.Name));
            grid.Columns.Add(x => x.Name);


            return grid;
        }

        private static IEnumerable<SimpleTerritory> FetchTerritoriesFromService()
        {
            var restService = new RestService("territories");
            var json = restService.Get();

            return JsonConvert.DeserializeObject<List<SimpleTerritory>>(json);
        }


        #endregion Methods
    }
}

CSRToolWebApp/Views/Territory/Add.cshtml
@model CSRToolWebApp.Models.TerritoryModel

@{

    ViewBag.Title = "Add Territory";
    Layout = "~/Views/Shared/Layouts/_PopUpLayout.cshtml";

}

@section ModalTitle
{
    <h2>@ViewBag.Title</h2>
}

@using (Html.BeginForm("Save", "Territory", new { @class = "form-horizontal", role = "form" }))
{

    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.TerritoryTypeId)

    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", autocomplete = "off", @maxlength = "50" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                @Html.LabelFor(model => model.ShortName, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.ShortName, new { @class = "form-control", autocomplete = "off", @maxlength = "50" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                @Html.LabelFor(model => model.TerritoryType, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.TerritoryType, new { @class = "form-control", autocomplete = "off" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.CheckBoxFor(model => model.IsActive)
                </div>
            </div>
        </div>
    </div>
    
    <div class="row"><div class="col-xs-12"><hr /></div></div>
    <div class="row">

        <div class="col-xs-11">
            <button class="btn btn-default btn-primary" type="button" data-dismiss="modal">Close</button>
            <button class="btn btn-default btn-primary" type="submit">Save</button>
        </div>

    </div>
}

CSRToolWebApp/Views/Territory/Default.cshtml
@using GridMvc.Html
@using Territory = CSRToolWebApp.DataContracts.Base.Territory

@model GridMvc.Grid<CSRToolWebApp.DataContracts.Base.SimpleTerritory>

@{
    ViewBag.Title = "Territories";
}

@*<div>
    @Html.Grid(Model).WithPaging(30).Sortable(true).Filterable(true)
</div>*@
<div>
    <div class="col-xs-2">
        @Html.Label("Territory", new { @class = "control-label" })
        @Html.DropDownList("TerritoryId", ViewBag.Territories as List<SelectListItem>, new { @class = "form-control" })
    </div>
</div>